#!/usr/bin/env ruby

$: << File.dirname(__FILE__)
require "lib/coursera_downloader"

module CourseraDownloader
  class Runner
    def self.run
      course_name = ARGV[0]
      email = ARGV[1]
      password = ARGV[2]
      file_store_dir = ARGV[3]

      course = CourseraDownloader::Course.new(course_name)
      course.login(email, password)

      policy = CourseraDownloader::Policy.new
      store = CourseraDownloader::FileStore.new(file_store_dir)
      downloader = CourseraDownloader::Downloader.new(course.cookie_file, policy, store)
      downloader.get(course.index_url)
    end
  end
end

CourseraDownloader::Runner.run
